#!/bin/bash

run_test_rom() {
    local FILENAME=$(basename "$1")
    printf "%-30s" "${FILENAME}"

    local OUTPUT=$(./build/emulator "$1" --headless --exit-on-infinite-jr)
    echo $OUTPUT | grep 'Failed' &> /dev/null

    if [ $? == 0 ]; then
        printf "\e[31mFailed\e[0m\n"
        return 1
    else
        printf "\e[32mPassed\e[0m\n"
        return 0
    fi
}

main() {
    local failed_test=0

    for test_rom in ./etc/test_roms/cpu_instrs/individual/*; do
        run_test_rom "$test_rom"

        if [ $? != 0 ]; then
            failed_test=1
        fi
    done

    return $failed_test
}

main
exit $?
