#pragma once
/* clang-format off */

static const std::string opcode_format_strings[256] = {
    "NOP",
    "LD BC,0x%04X",
    "LD (0x%04X),0x%02X",
    "INC BC",
    "INC B",
    "DEC B",
    "LD B,0x%02X",
    "RLCA",
    "LD (0x%04X),0x%04X",
    "ADD HL,0x%04X",
    "LD A,(0x%04X)",
    "DEC BC",
    "INC C",
    "DEC C",
    "LD C,0x%02X",
    "RRCA",

    "STOP",
    "LD DE,0x%04X",
    "LD (0x%04X),0x%02X",
    "INC DE",
    "INC D",
    "DEC D",
    "LD D,0x%02X",
    "RLA",
    "JR %d",
    "ADD HL,0x%04X",
    "LD A,(0x%04X)",
    "DEC DE",
    "INC E",
    "DEC E",
    "LD E,0x%02X",
    "RRA",

    "JR NZ,0x%02X",
    "LD HL,0x%04X",
    "LD (0x%04X+),0x%02X",
    "INC HL",
    "INC H",
    "DEC H",
    "LD H,0x%02X",
    "DAA",
    "JR Z,0x%02X",
    "ADD HL,0x%04X",
    "LD A,(0x%04X+)",
    "DEC HL",
    "INC L",
    "DEC L",
    "LD L,0x%02X",
    "CPL",

    "JR NC,0x%02X",
    "LD SP,0x%04X",
    "LD (0x%04X-),0x%02X",
    "INC SP",
    "INC (0x%04X)",
    "DEC (0x%04X)",
    "LD (0x%04X),0x%02X",
    "SCF",
    "JR C,0x%02X",
    "ADD HL,0x%04X",
    "LD A,(0x%04X-)",
    "DEC SP",
    "INC A",
    "DEC A",
    "LDA,0x%02X",
    "CCF",

    "LD B,0x%02X",
    "LD B,0x%02X",
    "LD B,0x%02X",
    "LD B,0x%02X",
    "LD B,0x%02X",
    "LD B,0x%02X",
    "LD B,(0x%04X)",
    "LD B,0x%02X",
    "LD C,0x%02X",
    "LD C,0x%02X",
    "LD C,0x%02X",
    "LD C,0x%02X",
    "LD C,0x%02X",
    "LD C,0x%02X",
    "LD C,(0x%04X)",
    "LD C,0x%02X",

    "LD D,0x%02X",
    "LD D,0x%02X",
    "LD D,0x%02X",
    "LD D,0x%02X",
    "LD D,0x%02X",
    "LD D,0x%02X",
    "LD D,(0x%04X)",
    "LD D,0x%02X",
    "LD E,0x%02X",
    "LD E,0x%02X",
    "LD E,0x%02X",
    "LD E,0x%02X",
    "LD E,0x%02X",
    "LD E,0x%02X",
    "LD E,(0x%04X)",
    "LD E,0x%02X",

    "LD H,0x%02X",
    "LD H,0x%02X",
    "LD H,0x%02X",
    "LD H,0x%02X",
    "LD H,0x%02X",
    "LD H,0x%02X",
    "LD H,(0x%04X)",
    "LD H,0x%02X",
    "LD L,0x%02X",
    "LD L,0x%02X",
    "LD L,0x%02X",
    "LD L,0x%02X",
    "LD L,0x%02X",
    "LD L,0x%02X",
    "LD L,(0x%04X)",
    "LD L,0x%02X",

    "LD (0x%04X),0x%02X",
    "LD (0x%04X),0x%02X",
    "LD (0x%04X),0x%02X",
    "LD (0x%04X),0x%02X",
    "LD (0x%04X),0x%02X",
    "LD (0x%04X),0x%02X",
    "HALT",
    "LD (0x%04X),0x%02X",
    "LD A,0x%02X",
    "LD A,0x%02X",
    "LD A,0x%02X",
    "LD A,0x%02X",
    "LD A,0x%02X",
    "LD A,0x%02X",
    "LD A,(0x%04X)",
    "LD A,0x%02X",

    "ADD A,0x%02X",
    "ADD A,0x%02X",
    "ADD A,0x%02X",
    "ADD A,0x%02X",
    "ADD A,0x%02X",
    "ADD A,0x%02X",
    "ADD A,(0x%04X)",
    "ADD A,0x%02X",
    "ADC A,0x%02X",
    "ADC A,0x%02X",
    "ADC A,0x%02X",
    "ADC A,0x%02X",
    "ADC A,0x%02X",
    "ADC A,0x%02X",
    "ADC A,(0x%04X)",
    "ADC A,0x%02X",

    "SUB B",
    "SUB C",
    "SUB D",
    "SUB E",
    "SUB H",
    "SUB L",
    "SUB (0x%04X)",
    "SUB A",
    "SBC A,0x%02X",
    "SBC A,0x%02X",
    "SBC A,0x%02X",
    "SBC A,0x%02X",
    "SBC A,0x%02X",
    "SBC A,0x%02X",
    "SBC A,(0x%04X)",
    "SBC A,0x%02X",

    "AND B",
    "AND C",
    "AND D",
    "AND E",
    "AND H",
    "AND L",
    "AND (0x%04X)",
    "AND A",
    "XOR B",
    "XOR C",
    "XOR D",
    "XOR E",
    "XOR H",
    "XOR L",
    "XOR (0x%04X)",
    "XOR A",

    "OR B",
    "OR C",
    "OR D",
    "OR E",
    "OR H",
    "OR L",
    "OR (0x%04X)",
    "OR A",
    "CP B",
    "CP C",
    "CP D",
    "CP E",
    "CP H",
    "CP L",
    "CP (0x%04X)",
    "CP A",

    "RET NZ",
    "POP BC",
    "JP NZ,0x%04X",
    "JP 0x%04X",
    "CALL NZ,0x%04X",
    "PUSH BC",
    "ADD A,0x%02X",
    "RST ",
    "RET Z",
    "RET",
    "JP Z,0x%04X",
    "cb opcode",
    "CALL Z,0x%04X",
    "CALL 0x%04X",
    "ADC A,0x%02X",
    "RST 0x08",

    "RET NC",
    "POP DE",
    "JP NC,0x%04X",
    "unused opcode",
    "CALL NC,0x%04X",
    "PUSH DE",
    "SUB 0x%02X",
    "RST 0x10",
    "RET C",
    "RETI",
    "JP C,0x%04X",
    "unused opcode",
    "CALL C,0x%04X",
    "unused opcode",
    "SBC A,0x%02X",
    "RST 0x18",

    "LD (0xFF00+0x%02X),0x%02X",
    "POP HL",
    "LD (0xFF00+0x%02X),0x%02X",
    "unused opcode",
    "unused opcode",
    "PUSH HL",
    "AND 0x%02X",
    "RST 0x20",
    "ADD SP,0x%02X",
    "JP (0x%04X)",
    "LD (0x%04X),0x%02X",
    "unused opcode",
    "unused opcode",
    "unused opcode",
    "XOR 0x%02X",
    "RST 0x28",

    "LD A,(0xFF00+0x%02X)",
    "POP AF",
    "LD A,(0xFF00+C)",
    "DI",
    "unused opcode",
    "PUSH AF",
    "OR 0x%02X",
    "RST 0x30",
    "LD HL,0x%04X",
    "LD SP,0x%04X",
    "LD A,(0x%04X)",
    "EI",
    "unused opcode",
    "unused opcode",
    "CP 0x%02X",
    "RST 0x38"
};

static const std::string opcode_cb_format_strings[256] = {
    "RLC B",
    "RLC C",
    "RLC D",
    "RLC E",
    "RLC H",
    "RLC L",
    "RLC (0x%04X)",
    "RLC A",
    "RRC B",
    "RRC C",
    "RRC D",
    "RRC E",
    "RRC H",
    "RRC L",
    "RRC (0x%04X)",
    "RRC A",

    "RL B",
    "RL C",
    "RL D",
    "RL E",
    "RL H",
    "RL L ",
    "RL (0x%04X)",
    "RL A",
    "RR B",
    "RR C",
    "RR D",
    "RR E",
    "RR H",
    "RR L",
    "RR (0x%04X)",
    "RR A",

    "SLA B",
    "SLA C",
    "SLA D",
    "SLA E",
    "SLA H",
    "SLA L",
    "SLA (0x%04X)",
    "SLA A",
    "SRA B",
    "SRA C",
    "SRA D",
    "SRA E",
    "SRA H",
    "SRA L",
    "SRA (0x%04X)",
    "SRA A",

    "SWAP B",
    "SWAP C",
    "SWAP D",
    "SWAP E",
    "SWAP H",
    "SWAP L",
    "SWAP (0x%04X)",
    "SWAP A",
    "SRL B",
    "SRL C",
    "SRL D",
    "SRL E",
    "SRL H",
    "SRL L",
    "SRL (0x%04X)",
    "SRL A",

    "BIT 0 B",
    "BIT 0 C",
    "BIT 0 D",
    "BIT 0 E",
    "BIT 0 H",
    "BIT 0 L",
    "BIT 0 (0x%04X)",
    "BIT 0 A",
    "BIT 1 B",
    "BIT 1 C",
    "BIT 1 D",
    "BIT 1 E",
    "BIT 1 H",
    "BIT 1 L",
    "BIT 1 (0x%04X)",
    "BIT 1 A",

    "BIT 2 B",
    "BIT 2 C",
    "BIT 2 D",
    "BIT 2 E",
    "BIT 2 H",
    "BIT 2 L",
    "BIT 2 (0x%04X)",
    "BIT 2 A",
    "BIT 3 B",
    "BIT 3 C",
    "BIT 3 D",
    "BIT 3 E",
    "BIT 3 H",
    "BIT 3 L",
    "BIT 3 (0x%04X)",
    "BIT 3 A",

    "BIT 4 B",
    "BIT 4 C",
    "BIT 4 D",
    "BIT 4 E",
    "BIT 4 H",
    "BIT 4 L",
    "BIT 4 (0x%04X)",
    "BIT 4 A",
    "BIT 5 B",
    "BIT 5 C",
    "BIT 5 D",
    "BIT 5 E",
    "BIT 5 H",
    "BIT 5 L",
    "BIT 5 (0x%04X)",
    "BIT 5 A",

    "BIT 6 B",
    "BIT 6 C",
    "BIT 6 D",
    "BIT 6 E",
    "BIT 6 H",
    "BIT 6 L",
    "BIT 6 (0x%04X)",
    "BIT 6 A",
    "BIT 7 B",
    "BIT 7 C",
    "BIT 7 D",
    "BIT 7 E",
    "BIT 7 H",
    "BIT 7 L",
    "BIT 7 (0x%04X)",
    "BIT 7 A",

    "RES 0 B",
    "RES 0 C",
    "RES 0 D",
    "RES 0 E",
    "RES 0 H",
    "RES 0 L",
    "RES 0 (0x%04X)",
    "RES 0 A",
    "RES 1 B",
    "RES 1 C",
    "RES 1 D",
    "RES 1 E",
    "RES 1 H",
    "RES 1 L",
    "RES 1 (0x%04X)",
    "RES 1 A",

    "RES 2 B",
    "RES 2 C",
    "RES 2 D",
    "RES 2 E",
    "RES 2 H",
    "RES 2 L",
    "RES 2 (0x%04X)",
    "RES 2 A",
    "RES 3 B",
    "RES 3 C",
    "RES 3 D",
    "RES 3 E",
    "RES 3 H",
    "RES 3 L",
    "RES 3 (0x%04X)",
    "RES 3 A",

    "RES 4 B",
    "RES 4 C",
    "RES 4 D",
    "RES 4 E",
    "RES 4 H",
    "RES 4 L",
    "RES 4 (0x%04X)",
    "RES 4 A",
    "RES 5 B",
    "RES 5 C",
    "RES 5 D",
    "RES 5 E",
    "RES 5 H",
    "RES 5 L",
    "RES 5 (0x%04X)",
    "RES 5 A",

    "RES 6 B",
    "RES 6 C",
    "RES 6 D",
    "RES 6 E",
    "RES 6 H",
    "RES 6 L",
    "RES 6 (0x%04X)",
    "RES 6 A",
    "RES 7 B",
    "RES 7 C",
    "RES 7 D",
    "RES 7 E",
    "RES 7 H",
    "RES 7 L",
    "RES 7 (0x%04X)",
    "RES 7 A",

    "SET 0 B",
    "SET 0 C",
    "SET 0 D",
    "SET 0 E",
    "SET 0 H",
    "SET 0 L",
    "SET 0 (0x%04X)",
    "SET 0 A",
    "SET 1 B",
    "SET 1 C",
    "SET 1 D",
    "SET 1 E",
    "SET 1 H",
    "SET 1 L",
    "SET 1 (0x%04X)",
    "SET 1 A",

    "SET 2 B",
    "SET 2 C",
    "SET 2 D",
    "SET 2 E",
    "SET 2 H",
    "SET 2 L",
    "SET 2 (0x%04X)",
    "SET 2 A",
    "SET 3 B",
    "SET 3 C",
    "SET 3 D",
    "SET 3 E",
    "SET 3 H",
    "SET 3 L",
    "SET 3 (0x%04X)",
    "SET 3 A",

    "SET 4 B",
    "SET 4 C",
    "SET 4 D",
    "SET 4 E",
    "SET 4 H",
    "SET 4 L",
    "SET 4 (0x%04X)",
    "SET 4 A",
    "SET 5 B",
    "SET 5 C",
    "SET 5 D",
    "SET 5 E",
    "SET 5 H",
    "SET 5 L",
    "SET 5 (0x%04X)",
    "SET 5 A",

    "SET 6 B",
    "SET 6 C",
    "SET 6 D",
    "SET 6 E",
    "SET 6 H",
    "SET 6 L",
    "SET 6 (0x%04X)",
    "SET 6 A",
    "SET 7 B",
    "SET 7 C",
    "SET 7 D",
    "SET 7 E",
    "SET 7 H",
    "SET 7 L",
    "SET 7 (0x%04X)",
    "SET 7 A"
};
